### ISSUE TITLE
19.07分支可否加入ACRH17型號

### ISSUE THREAD

**Issue by kai456789** [project-openwrt/openwrt#130]
19.07分支可否加入ACRH17型號

![2020 04 11-19_25_40](https://user-images.githubusercontent.com/720118/79042429-63058c00-7c2a-11ea-8e54-c30a08165135.png)

**Comment by AmadeusGhost** [comment]
可以，等明天

**Comment by AmadeusGhost** [comment]
已支持，没问题请自行关闭issue

**Comment by kai456789** [comment]
感謝 更新源碼後已看到 來編譯試試
