### ISSUE TITLE
咨询luci问题

### ISSUE THREAD

**Issue by fuqiang03** [project-openwrt/openwrt#131]
由于luci更新
官方使用了ACLs
有什么办法兼容以前的配置读取吗

**Comment by zxlhhyccc** [comment]
> 由于luci更新
> 官方使用了ACLs
> 有什么办法兼容以前的配置读取吗

暂时等吧

**Comment by 1715173329** [comment]
You may simply revert the commit openwrt/luci@c099344 to make everything works as usual.
Besides, I've added the ACL files, hoping them will work fine.

**Comment by fuqiang03** [comment]
@1715173329 
遇到过这个问题吗
![QQ截图20200424214603](https://user-images.githubusercontent.com/26851715/80219501-251a5600-8675-11ea-92df-c10a1a3fe634.png)
不可描述软件plus  和dnsmasq.d建立的文件冲突

**Comment by 1715173329** [comment]
手动创建下这个文件夹即可

**Comment by fuqiang03** [comment]
这个文件夹是存在的

**Comment by fuqiang03** [comment]
![QQ截图20200424220809](https://user-images.githubusercontent.com/26851715/80221679-3a44b400-8678-11ea-9486-5730c242c877.png)
这有这样才能正常 否则崩溃 不之原因
![QQ截图20200424220853](https://user-images.githubusercontent.com/26851715/80221761-52b4ce80-8678-11ea-867b-5cfad17cf0bb.png)

**Comment by fuqiang03** [comment]
@1715173329 
大神看看你那有这样的情况吗
全部使用主库源码

**Comment by 1715173329** [comment]
我萌新
没遇到过
应该是 `/etc/dnsmasq.d` 文件夹缺失

**Comment by fuqiang03** [comment]
这两个文件夹都是存在的 好像是不可描述软件创建的

**Comment by fuqiang03** [comment]
不知道注释掉会有什么影响
![QQ截图20200424220809](https://user-images.githubusercontent.com/26851715/80226739-5435c500-867f-11ea-8ab2-935f929fad33.png)
