### ISSUE TITLE
19.07編譯套件選上SSR+報錯

### ISSUE THREAD

**Issue by kai456789** [project-openwrt/openwrt#132]
19.07分支編譯套件選上SSR+ 會報錯 
機型 ACRH17 
日誌如下
echo "libpolarssl" >> /home/k/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/pkginfo/polarssl.default.install
make[3]: Leaving directory '/home/k/openwrt/package/lean/polarssl'
time: package/lean/polarssl/compile#0.16#0.16#1.88
make[3]: Entering directory '/home/k/openwrt/package/lean/shadowsocksr-libev'
mkdir -p /home/k/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/stamp
SHELL= flock /home/k/openwrt/tmp/.root-copy.flock -c 'cp -fpR /home/k/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/shadowsocksr-libev//shadowsocksr-libev-2.5.6-d63ff863800a5645aca4309d5dd5962bd1e95543/.pkgdir/shadowsocksr-libev-alt/. /home/k/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/'
touch /home/k/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/stamp/.shadowsocksr-libev-alt_installed
echo "shadowsocksr-libev-alt" >> /home/k/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/pkginfo/shadowsocksr-libev.default.install
mkdir -p /home/k/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/stamp
SHELL= flock /home/k/openwrt/tmp/.root-copy.flock -c 'cp -fpR /home/k/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/shadowsocksr-libev//shadowsocksr-libev-2.5.6-d63ff863800a5645aca4309d5dd5962bd1e95543/.pkgdir/shadowsocksr-libev-server/. /home/k/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/'
touch /home/k/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/stamp/.shadowsocksr-libev-server_installed
echo "shadowsocksr-libev-server" >> /home/k/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/pkginfo/shadowsocksr-libev.default.install
mkdir -p /home/k/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/stamp
SHELL= flock /home/k/openwrt/tmp/.root-copy.flock -c 'cp -fpR /home/k/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/shadowsocksr-libev//shadowsocksr-libev-2.5.6-d63ff863800a5645aca4309d5dd5962bd1e95543/.pkgdir/shadowsocksr-libev-ssr-local/. /home/k/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/'
touch /home/k/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/stamp/.shadowsocksr-libev-ssr-local_installed
echo "shadowsocksr-libev-ssr-local" >> /home/k/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/pkginfo/shadowsocksr-libev.default.install
make[3]: Leaving directory '/home/k/openwrt/package/lean/shadowsocksr-libev'
time: package/lean/shadowsocksr-libev/compile#0.08#0.16#0.50
make[3]: Entering directory '/home/k/openwrt/package/lean/tcpping'
mkdir -p /home/k/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/stamp
SHELL= flock /home/k/openwrt/tmp/.root-copy.flock -c 'cp -fpR /home/k/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/tcpping-0.2/.pkgdir/tcpping/. /home/k/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/'
touch /home/k/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/root-ipq40xx/stamp/.tcpping_installed
mkdir -p /home/k/openwrt/bin/targets/ipq40xx/generic/packages /home/k/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/tcpping-0.2/ipkg-arm_cortex-a7_neon-vfpv4/tcpping/CONTROL /home/k/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/pkginfo
install -d -m0755 /home/k/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/tcpping-0.2/ipkg-arm_cortex-a7_neon-vfpv4/tcpping/usr/bin
install -m0755 /home/k/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/tcpping-0.2/tcpping /home/k/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/tcpping-0.2/ipkg-arm_cortex-a7_neon-vfpv4/tcpping/usr/bin/tcpping
find /home/k/openwrt/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/tcpping-0.2/ipkg-arm_cortex-a7_neon-vfpv4/tcpping -name 'CVS' -o -name '.svn' -o -name '.#*' -o -name '*~'| xargs -r rm -rf
Package tcpping is missing dependencies for the following libraries:
libpcap.so.1
Makefile:38: recipe for target '/home/k/openwrt/bin/packages/arm_cortex-a7_neon-vfpv4/base/tcpping_0.2-d890cc1bd8e3951390ceeff1ccb092a5d802850c_arm_cortex-a7_neon-vfpv4.ipk' failed
make[3]: *** [/home/k/openwrt/bin/packages/arm_cortex-a7_neon-vfpv4/base/tcpping_0.2-d890cc1bd8e3951390ceeff1ccb092a5d802850c_arm_cortex-a7_neon-vfpv4.ipk] Error 1
make[3]: Leaving directory '/home/k/openwrt/package/lean/tcpping'
time: package/lean/tcpping/compile#0.09#0.05#0.35
package/Makefile:111: recipe for target 'package/lean/tcpping/compile' failed
make[2]: *** [package/lean/tcpping/compile] Error 2
make[2]: Leaving directory '/home/k/openwrt'
package/Makefile:107: recipe for target '/home/k/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/stamp/.package_compile' failed
make[1]: *** [/home/k/openwrt/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/k/openwrt'
/home/k/openwrt/include/toplevel.mk:225: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by AmadeusGhost** [comment]
![make](https://user-images.githubusercontent.com/42570690/79202562-612b0b00-7e6c-11ea-913d-a421dca4342d.png)
试了下没有问题，正常编译
