### ISSUE TITLE
master分支编译passwall失败

### ISSUE THREAD

**Issue by ClayMoreBoy** [project-openwrt/openwrt#133]
https://github.com/ClayMoreBoy/OpenWrt-Actions-R7800/runs/586048242?check_suite_focus=true#step:10:18119
@1715173329

**Comment by 1715173329** [comment]
Please paste the error log to **here** or https://pastebin.ubuntu.com.

**Comment by zxlhhyccc** [comment]
> https://github.com/ClayMoreBoy/OpenWrt-Actions-R7800/runs/586048242?check_suite_focus=true#step:10:18119
> @1715173329
luci-app-passwall的报错，但是我编译正常。。。请自行找原因。。。。

**Comment by AmadeusGhost** [comment]
This was already fix in project-openwrt/openwrt@518025b by dalao.
顺便说一下，下次再不给具体编译失败的日志而是直接扔action的话直接拉黑。
