### ISSUE TITLE
能否将Hill-98版的k3screenctrl替换成lwz322版的k3screenctrl

### ISSUE THREAD

**Issue by BlackTouma** [project-openwrt/openwrt#134]
Hill-98版本有较多BUG且最后更新为3年前，lwz322版在其基础上修复目前依旧保持更新。

项目相关地址：

https://github.com/lwz322/k3screenctrl

https://github.com/lwz322/luci-app-k3screenctrl

https://github.com/lwz322/k3screenctrl_build

感激不尽。

**Comment by zxlhhyccc** [comment]
> Hill-98版本有较多BUG且最后更新为3年前，lwz322版在其基础上修复目前依旧保持更新。
> 
> 项目相关地址：
> 
> https://github.com/lwz322/k3screenctrl
> 
> https://github.com/lwz322/luci-app-k3screenctrl
> 
> https://github.com/lwz322/k3screenctrl_build
> 
> 感激不尽。

原理是一样的，其实我的源码host.sh与lwz322的源码不一样（其实就是主库里的源码），如果你确实需要替换，你把仓库里的屏幕源码删掉，然后替换lwz322的源码即可。。。。

**Comment by BlackTouma** [comment]
好嘞，明白啦。。。
主要是lwz322版本还在修复屏幕睡死的BUG，Hill-98版偶尔会屏幕睡死。还有一个问题，Hill-98版的天气貌似显示不出来温度。。。
