### ISSUE TITLE
master分支RPCError错误

### ISSUE THREAD

**Issue by yangsongli** [project-openwrt/openwrt#141]
错误软件有frpc,transmission
![image](https://user-images.githubusercontent.com/52395039/79585141-f4c93980-8101-11ea-9f52-ec669e2d62b2.png)
![image](https://user-images.githubusercontent.com/52395039/79585195-07dc0980-8102-11ea-97a8-f10591658761.png)

**Comment by 1715173329** [comment]
@yangsongli 等官方慢慢修吧。

**Comment by yangsongli** [comment]
> @yangsongli等官方慢慢修吧。

看来果然是官方的错误
