### ISSUE TITLE
開啟ADGUARD HOME IPV4無法上網

### ISSUE THREAD

**Issue by kai456789** [project-openwrt/openwrt#144]
型號ASUS RT-ACRH17 
架構ARMv7 Processor rev 5 (v7l) x 4
固件版本OpenWrt 18.06 by Lean  | Mod20.04 by CTCGFW /LuCI 18.06 by Lean (Mod20.04 by CTCGFW)
內核版本4.19.115

ADG取代53端口 防火牆也註釋掉53端口優先權
開啟ADG後 一陣子後IPV4會變的無法上網 使用IPV6則正常
去接口關閉LAN的DHCP 使用ADG本身的DHCP則IPV4跟IPV6都能正常上網 
但網易雲解鎖就會失效 無法劫持

**Comment by 1715173329** [comment]
不用即可。
