### ISSUE TITLE
石像鬼插件无法开启。

### ISSUE THREAD

**Issue by ledewrt** [project-openwrt/openwrt#147]
大佬，编译好石像鬼插件，点击全局设置-启用qos，然后提示：
/usr/lib/lua/luci/dispatcher.lua:381: Failed to execute cbi dispatcher target for entry '/admin/network/qos_gargoyle/global'.
The called action terminated with an exception:
/usr/lib/lua/luci/cbi.lua:1027: attempt to concatenate local 't' (a nil value)
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:381: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:95: in function </usr/lib/lua/luci/dispatcher.lua:94>

求修复。

**Comment by 1715173329** [comment]
OpenWrt 19.07.2 or later?

**Comment by ledewrt** [comment]
18.06

**Comment by 1715173329** [comment]
这个 LuCI 懒得修了，老掉牙了都，用其他 QoS 代替吧

**Comment by zxlhhyccc** [comment]
> openwrt-18.06

1806的话，有可以使用的。。。

**Comment by ledewrt** [comment]
好的
