### ISSUE TITLE
ssrserver-python  依賴切到python3後 會提示缺失python

### ISSUE THREAD

**Issue by kai456789** [project-openwrt/openwrt#148]
固件版本 | OpenWrt 18.06 by Lean \| Mod20.04 by CTCGFW / LuCI 18.06 by Lean (Mod20.04 by CTCGFW)
-- | --
内核版本 | 4.19.120  X86

![Screenshot (1)](https://user-images.githubusercontent.com/720118/80947250-55ef4d80-8e22-11ea-82b2-b9523e240ad3.png)

![Screenshot](https://user-images.githubusercontent.com/720118/80947264-5daef200-8e22-11ea-90af-284764df5f00.png)

自行用 OPKG裝上 python 可解決

**Comment by 1715173329** [comment]
请运行 `git pull` 后进行编译刷入并检查是否正常工作。

**Comment by kai456789** [comment]
git pull 後 已正常 感謝
![Screenshot](https://user-images.githubusercontent.com/720118/81027924-0fe1ca80-8eb2-11ea-9f2d-797001af2225.png)
