### ISSUE TITLE
能不能把mysql和php5融合到里面去？自己把上面两个源码拉进去编译老是错误

### ISSUE THREAD

**Issue by dzhuqi** [project-openwrt/openwrt#15]
能不能把mysql和php5融合到里面去？自己把上面两个源码拉进去编译老是错误

**Comment by 1715173329** [comment]
@dzhuqi MySQL&PHP都是加进去了的

**Comment by dzhuqi** [comment]
@1715173329 看到mysql了 我加个php5编译试试，昨晚没有看清。又从cc版拉了个mysql过去
