### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by fuqiang03** [project-openwrt/openwrt#151]
gost 执行文件必须更新后才能编译了

**Comment by 1715173329** [comment]
？意义不明

**Comment by fuqiang03** [comment]
额 就是gost 源码 已经更新了
![image](https://user-images.githubusercontent.com/26851715/82754869-7186bc00-9e02-11ea-8850-537ef15abb01.png)
老版本编译会报错的

**Comment by fuqiang03** [comment]
但是新版的我也没跑一遍不知道什么样呢

**Comment by 1715173329** [comment]
@fuqiang03 旧版本构建没问题啊

**Comment by fuqiang03** [comment]
![QQ截图20200524211241](https://user-images.githubusercontent.com/26851715/82754989-55cfe580-9e03-11ea-93e3-de55036eee17.png)
![image](https://user-images.githubusercontent.com/26851715/82754999-6e400000-9e03-11ea-91dd-d44b2aaabc44.png)
这是我自己打的补丁 不修改是过不去了
