### ISSUE TITLE
应用过滤报错了

### ISSUE THREAD

**Issue by ledewrt** [project-openwrt/openwrt#159]
/usr/lib/lua/luci/dispatcher.lua:381: Failed to execute cbi dispatcher target for entry '/admin/control/appfilter'.
The called action terminated with an exception:
/usr/lib/lua/luci/model/cbi/appfilter/appfilter.lua:89: attempt to index local 't' (a nil value)
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:381: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:95: in function </usr/lib/lua/luci/dispatcher.lua:94>

**Comment by AmadeusGhost** [comment]
哪个分支？

**Comment by ledewrt** [comment]
18.06  默认的
