### ISSUE TITLE
问题反馈AdGuardHome

### ISSUE THREAD

**Issue by fuqiang03** [project-openwrt/openwrt#170]
define Package/AdGuardHome/install
	$(call GoPackage/Package/Install/Bin,$(PKG_INSTALL_DIR))
	$(INSTALL_DIR) $(1)/usr/bin/AdGuardHome
	$(INSTALL_BIN) $(PKG_INSTALL_DIR)/usr/bin/AdGuardHome $(1)/usr/bin/AdGuardHome/AdGuardHome

和配置文件路径保持一致

虽然客户端执行了,但是无法打开页面.
![QQ截图20200720162743](https://user-images.githubusercontent.com/26851715/87916529-286f8300-caa6-11ea-9cce-e17d81bf448f.png)
![QQ截图20200720162753](https://user-images.githubusercontent.com/26851715/87916532-29081980-caa6-11ea-8d24-39161e5121c6.png)

**Comment by fuqiang03** [comment]
使用源码作者的客户端没有这些问题
我只是想说可能在AdGuardHome 编译的时候缺少了什么东西
![QQ截图20200720164032](https://user-images.githubusercontent.com/26851715/87917721-fa8b3e00-caa7-11ea-9a54-6b38fa369c09.png)
![QQ截图20200720164040](https://user-images.githubusercontent.com/26851715/87917727-fc550180-caa7-11ea-958f-f6f0c016df34.png)

**Comment by fuqiang03** [comment]
@1715173329 
![QQ截图20200727195639](https://user-images.githubusercontent.com/26851715/88539245-7acf1780-d043-11ea-9730-80892d47683c.png)
请问有GitHub上的资源可以替代吗的(go.mod go.sum),或者其他的办法,谢谢
由于无法翻墙所以造成了上面的错误

**Comment by 1715173329** [comment]
设置个 GOPROXY 应该就行，你可以谷歌看看

**Comment by fuqiang03** [comment]
ifeq ($(CONFIG_AdGuardHome_COMPRESS_GOPROXY),y)
export GO111MODULE=on
export GOPROXY=https://goproxy.cn
endif
这样的地址可以吗

**Comment by fuqiang03** [comment]
@1715173329 加了代理也是无效的 改了go.mod go.sum文件也不行
![QQ截图20200801224811](https://user-images.githubusercontent.com/26851715/89104115-64f99200-d449-11ea-9485-2aa425b2c80e.png)
![QQ截图20200801224820](https://user-images.githubusercontent.com/26851715/89104117-65922880-d449-11ea-9b60-3220ab597d00.png)

**Comment by 1715173329** [comment]
那就加钱换梯子

**Comment by QiuSimons** [comment]
> @1715173329
> ![QQ截图20200727195639](https://user-images.githubusercontent.com/26851715/88539245-7acf1780-d043-11ea-9730-80892d47683c.png)
> 请问有GitHub上的资源可以替代吗的(go.mod go.sum),或者其他的办法,谢谢
> 由于无法翻墙所以造成了上面的错误

用action跑呗，墙外环境编译（doge

**Comment by fuqiang03** [comment]
没有梯子真的不方便 其他的都可以用代理 只有这个不行 不知道问题出在哪里
