### ISSUE TITLE
极路由X 没有mwan3，求极路由编译配置文件

### ISSUE THREAD

**Issue by tanpengsccd** [project-openwrt/openwrt#173]
固件自https://www.right.com.cn/forum/thread-4019506-1-1.html。
源里的mwan  安装会提示内核过低。

**Comment by PassWall-OpenWrt** [comment]
> 固件自[https://www.right.com.cn/forum/thread-4019506-1-1.html。](https://www.right.com.cn/forum/thread-4019506-1-1.html%E3%80%82)
> 源里的mwan 安装会提示内核过低。

配置文件？源码在这里 自己按照编译教程自行编译即可。

**Comment by AmadeusGhost** [comment]
@tanpengsccd 说真的，你自己编译的时候选上 mwan3 相关的包不就可以了吗
