### ISSUE TITLE
求SORA大佬接手Zerotier，修复下目前LUCI的BUG

### ISSUE THREAD

**Issue by mjyhj** [project-openwrt/openwrt#174]
1.在lUCI多network id 只会join，不会leavel，保存过后删除LUCI上ID， 还是会多个ID运行
2.日志里只能读取单个network id，多个就会失效
3.设置多ID，添加防火墙规则经常只会添加一个ID或者直接不能添加，导致只有一个ID通
4.路由不重启一直联网的话，PPPOE 重连换IP后，后台会掉线，或者变成大延迟 打洞失败

**Comment by 1715173329** [comment]
1,2,3 已修，4 问题请联系 ZeroTier 官方。
