### ISSUE TITLE
编译大麦DW33D失败

### ISSUE THREAD

**Issue by wifiway520** [project-openwrt/openwrt#185]
编译4.9失败，4.14可以成功，但很多插件选择了没有，不知道能不能修复，感谢！

**Comment by AmadeusGhost** [comment]
失败是哪里失败，选择了没有又是什么意思 ...？

**Comment by 1715173329** [comment]
@wifiway520 就你给的这点信息，还不给我们打钱，很难帮你办事啊

**Comment by PassWall-OpenWrt** [comment]
@wifiway520 还原官方Uboot ,使用OpenWrt官方最新master源码编译 或者下官方snapshot使用。[https://www.right.com.cn/forum/thread-433702-1-1.html](url)
[https://www.right.com.cn/forum/thread-4042256-1-1.html](url)
[https://downloads.openwrt.org/snapshots/targets/ath79/nand/](url)

**Comment by AmadeusGhost** [comment]
@wifiway520 What is your problem?
