### ISSUE TITLE
可否给Openwrt-19.07加上efi引导呢

### ISSUE THREAD

**Issue by ghost** [project-openwrt/openwrt#188]

**Comment by AmadeusGhost** [comment]
人呢...？😮

**Comment by Teaffanie** [comment]
看到了，感谢dalao

**Comment by AmadeusGhost** [comment]
我萌新， https://github.com/project-openwrt/openwrt/commit/ced7cd5d911a27e9247dc329376e6668b4c69f69 Can you test this?

**Comment by Teaffanie** [comment]
> 我萌新， ced7cd5 Can you test this?

开始编译了

**Comment by Teaffanie** [comment]
> 我萌新， [ced7cd5](https://github.com/project-openwrt/openwrt/commit/ced7cd5d911a27e9247dc329376e6668b4c69f69) Can you test this?

报错了。
grub-mkimage: error: cannot open `/workdir/openwrt/staging_dir/host/lib/grub/i386-pc/moddep.lst': No such file or directory.
2779
cp -fpR /workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/bzImage /workdir/openwrt/build_dir/target-x86_64_musl/linux-x86_64/root.grub/boot/vmlinuz
2780
make[5]: *** [install-images] Error 1

**Comment by AmadeusGhost** [comment]
> 报错了。
> make[5]: *** [install-images] Error 1
> https://github.com/Teaffanie/bygj/runs/1085478096?check_suite_focus=true

现在应该可以了 (just my mistake)

**Comment by Teaffanie** [comment]
> 现在应该可以了 (just my mistake)
编译成功并且正常使用了
