### ISSUE TITLE
rtl8821cu编译成功但出现问题

### ISSUE THREAD

**Issue by CMCCAdmin** [project-openwrt/openwrt#191]
设备：树莓派4b，编译成功插入USB dmesg报错，luci出现好多未关联的无线配置，然后通过luci修改无线配置页面长时间无响应。网卡用的是comfast 811ac rtl8811cu芯片
openwrt kernel 4.19.123
dmesg
[   40.741233] usb 1-1.1: new high-speed USB device number 4 using xhci_hcd
[   40.871740] usb 1-1.1: New USB device found, idVendor=0bda, idProduct=c811, bcdDevice= 2.00
[   40.880105] usb 1-1.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[   40.887450] usb 1-1.1: Product: 802.11ac NIC
[   40.891735] usb 1-1.1: Manufacturer: Realtek
[   40.896004] usb 1-1.1: SerialNumber: 123456
[   40.904046] RTW: [HALMAC]11692M
               HALMAC_MAJOR_VER = 1
               HALMAC_PROTOTYPE_VER = 4
               HALMAC_MINOR_VER = 19
               HALMAC_PATCH_VER = 3
[   40.921409] RTW: ERROR [HALMAC][ERR]Dump efuse in suspend
[   41.057084] RTW: HW EFUSE
[   41.059726] RTW: 0x000: 29 81 00 BC  09 00 21 00  6E 04 A4 10  10 00 30 0B
[   41.066808] RTW: 0x010: 23 23 23 23  23 23 2B 2B  2B 2B 2B 02  FF FF FF FF
[   41.073888] RTW: 0x020: FF FF 24 24  24 24 22 23  23 24 24 25  22 22 22 22
[   41.080947] RTW: 0x030: 24 FF FF FF  FF FF D0 FF  FF FF 23 23  23 23 23 23
[   41.088012] RTW: 0x040: 2B 2B 2B 2B  2B 02 FF FF  FF FF FF FF  FF FF FF FF
[   41.095084] RTW: 0x050: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF
[   41.102150] RTW: 0x060: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF
[   41.109210] RTW: 0x070: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF
[   41.116282] RTW: 0x080: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF
[   41.123348] RTW: 0x090: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF
[   41.130413] RTW: 0x0A0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF
[   41.137481] RTW: 0x0B0: FF FF FF FF  FF FF FF FF  7F 33 19 00  FF FF FF FF
[   41.144555] RTW: 0x0C0: FF 22 00 41  00 00 00 00  00 FF 22 FF  FF FF FF FF
[   41.151624] RTW: 0x0D0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF
[   41.158686] RTW: 0x0E0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF
[   41.165749] RTW: 0x0F0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF
[   41.172822] RTW: 0x100: DA 0B 11 C8  E3 46 02 20  0D B0 36 AA  30 09 03 52
[   41.179879] RTW: 0x110: 65 61 6C 74  65 6B 0E 03  38 30 32 2E  31 31 61 63
[   41.186944] RTW: 0x120: 20 4E 49 43  08 03 31 32  33 34 35 36  FF FF FF FF
[   41.194015] RTW: 0x130: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF
[   41.201071] RTW: 0x140: FF FF FF FF  00 00 31 0F  FF FF FF FF  FF FF FF FF
[   41.208135] RTW: 0x150: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF
[   41.215205] RTW: 0x160: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF
[   41.222270] RTW: 0x170: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF
[   41.229329] RTW: 0x180: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF
[   41.236394] RTW: 0x190: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF
[   41.243461] RTW: 0x1A0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF
[   41.250556] RTW: 0x1B0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF
[   41.257628] RTW: 0x1C0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF
[   41.264700] RTW: 0x1D0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF
[   41.271762] RTW: 0x1E0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF
[   41.278822] RTW: 0x1F0: FF FF FF FF  FF FF FF FF  FF FF FF FF  FF FF FF FF
[   41.286109] RTW: hal_com_config_channel_plan chplan:0x7F
[   41.298775] RTW: [HALMAC][ALWAYS]shall R reg twice!!
[   41.305581] RTW: WARN [HALMAC][WARN]H2C/C2H ver is compatible!!
[   41.395736] RTW: ERROR [HALMAC][ERR]Dump efuse in suspend
[   41.401293] RTW: ERROR [HALMAC][ERR]Dump efuse in suspend
[   41.406842] RTW: ERROR [HALMAC][ERR]Dump efuse in suspend
[   41.412396] RTW: ERROR [HALMAC][ERR]Dump efuse in suspend
[   41.417938] RTW: ERROR [HALMAC][ERR]Dump efuse in suspend
[   41.423484] RTW: ERROR [HALMAC][ERR]Dump efuse in suspend
[   41.429014] RTW: ERROR [HALMAC][ERR]Dump efuse in suspend
[   41.435438] RTW: rtw_regsty_chk_target_tx_power_valid return _FALSE for band:0, path:0, rs:0, t:-1
[   41.446563] RTW: rtw_ndev_init(wlan1) if1 mac_addr=20:0d:b0:36:aa:30
[   41.457459] RTW: rtw_ndev_init(wlan2) if2 mac_addr=22:0d:b0:36:aa:30

iwinfo

wlan1     ESSID: unknown
          Access Point: 20:0D:B0:36:AA:30
          Mode: Client  Channel: unknown (unknown)
          Tx-Power: 12 dBm  Link Quality: unknown/70
          Signal: unknown  Noise: unknown
          Bit Rate: unknown
          Encryption: unknown
          Type: nl80211  HW Mode(s): 802.11abg
          Hardware: unknown [Generic MAC80211]
          TX power offset: unknown
          Frequency offset: unknown
          Supports VAPs: no  PHY name: phy1

wlan2     ESSID: unknown
          Access Point: 22:0D:B0:36:AA:30
          Mode: Client  Channel: unknown (unknown)
          Tx-Power: 12 dBm  Link Quality: unknown/70
          Signal: unknown  Noise: unknown
          Bit Rate: unknown
          Encryption: unknown
          Type: nl80211  HW Mode(s): 802.11abg
          Hardware: unknown [Generic MAC80211]
          TX power offset: unknown
          Frequency offset: unknown
          Supports VAPs: no  PHY name: phy2

**Comment by AmadeusGhost** [comment]
rtl 驱动并不支持通过 iwinfo 和 openwrt 的 nl80211 或者 wext 框架进行操作，所以无法通过 luci 进行控制。
