### ISSUE TITLE
Htop build failed in ubuntu 20.04

### ISSUE THREAD

**Issue by ksong008** [project-openwrt/openwrt#205]
HTOP升级后的patch有问题，删除patch后，arm设备能正常编译，x86貌似没影响

**Comment by AmadeusGhost** [comment]
哪个分支？

**Comment by ksong008** [comment]
@AmadeusGhost master，k5.4都一样

**Comment by AmadeusGhost** [comment]
![k5.4](https://user-images.githubusercontent.com/42570690/93068941-abc8e180-f6af-11ea-9107-7c00e7c51471.png)
我在 k5.4 （ipq40xx）上试了下好像没问题诶

**Comment by ksong008** [comment]
@AmadeusGhost 5.4是别人反馈的，今天我试了下master，boom
ps:能不能回群里说，这比tg还tg

**Comment by AmadeusGhost** [comment]
u1s1，issue 反馈 bug 更为合适，加上最近事情太多了（天天都不在宿舍那种），我也只能只看 issue
跑了下应该并不是 htop 的问题，master 上 samba 36 是炸了，我等会看下 commit，直接 drop 掉算了

**Comment by ksong008** [comment]
你 make clean 跑一下看看

**Comment by ksong008** [comment]
> u1s1，issue 反馈 bug 更为合适，加上最近事情太多了（天天都不在宿舍那种），我也只能只看 issue
> 跑了下应该并不是 htop 的问题，master 上 samba 36 是炸了，我等会看下 commit，直接 drop 掉算了
你抽空，make clean跑下看看

**Comment by AmadeusGhost** [comment]
> 你抽空，make clean跑下看看

就是全新编译的 master 代码😂

**Comment by AmadeusGhost** [comment]
> 你抽空，make clean跑下看看

已测试移除 samba36 后 ipq40xx 全新编译正常

**Comment by 1715173329** [comment]
> master 上 samba 36 是炸了

@AmadeusGhost 我记得这个不是早就被 drop 掉了么。。

**Comment by AmadeusGhost** [comment]
> 我记得这个不是早就被 drop 掉了么。。

官方是早 drop 了，不过之前 merge 的时候跳过了，毕竟 samba4 编译要多不少时间（小声
![cai](https://user-images.githubusercontent.com/42570690/93097752-8ac8b680-f6d8-11ea-9d61-22f0d81d2cde.jpg)

**Comment by ksong008** [comment]
> ![k5.4](https://user-images.githubusercontent.com/42570690/93068941-abc8e180-f6af-11ea-9107-7c00e7c51471.png)
> 我在 k5.4 （ipq40xx）上试了下好像没问题诶
![image](https://user-images.githubusercontent.com/54489832/93099719-edbb4d00-f6da-11ea-96a5-585d747d6161.png)

**Comment by 1715173329** [comment]
> > 我记得这个不是早就被 drop 掉了么。。
> 
> 官方是早 drop 了，不过之前 merge 的时候跳过了，毕竟 samba4 编译要多不少时间（小声
> ![cai](https://user-images.githubusercontent.com/42570690/93097752-8ac8b680-f6d8-11ea-9d61-22f0d81d2cde.jpg)

天天刷这张烂图有意思¿

**Comment by 1715173329** [comment]
另外麻烦以后 merge 不要混杂其他无关更改，否则将会难以定位

**Comment by AmadeusGhost** [comment]
> ![image](https://user-images.githubusercontent.com/54489832/93099719-edbb4d00-f6da-11ea-96a5-585d747d6161.png)

这个我 master 编译是能过的😂

> 天天刷这张烂图有意思¿

您觉得是烂图那把我 t 了即可，眼不见心为静

**Comment by MYMLD** [comment]
你们别吵了，图片是我的，确定如此，UB系统20. dl是全的，真过不了，已经删除了整个HTOP文件夹，然后编译 一切正常，
没更新之前上个分支K5.4 内核是5.461一切正常 ，后来更新到现在的版本5.465 分支K5.4 及主分支 同样的报错～K54分支删除HTOP目录编译一切正常，现在编译的是主分支，同样必须删除了HTOP才能过，先删除的是HTOP目录中的001xxx文件，过不了，只有整个目录删除了 ，偶是小白````勿取笑拉

**Comment by AmadeusGhost** [comment]
20.04 啊，那确实不大一样

**Comment by 1715173329** [comment]
@MYMLD 您的图片无问题

htop 来自于上游源码，目前我在 rockchip (based on Ubuntu 18.04) 上测试正常，其他的未详细测试
这周有空我看看什么情况，或者等 @AmadeusGhost 大佬看看。

**Comment by 1715173329** [comment]
> > 天天刷这张烂图有意思¿
> 
> 您觉得是烂图那把我 t 了即可，眼不见心为静

你大可

**Comment by 1715173329** [comment]
> > 天天刷这张烂图有意思¿
> 
> 您觉得是烂图那把我 t 了即可，眼不见心为静

你大可不必找任何借口或理由搪塞或转移话题，我只想讨论问题本身

**Comment by ksong008** [comment]
> 20.04 啊，那确实不大一样

其实，我早上也失败的，删了patch之后通过，然后没法复原了…哪怕是make clean...

**Comment by AmadeusGhost** [comment]
> 其实，我早上也失败的，删了patch之后通过，然后没法复原了…哪怕是make clean...

说真的，信息最好能给多少给多少，不然不知道具体啥问题 😂
> 你大可

好啊，反正咱对于这里而言只有 noise，这边建议您直接 reply to me with /ban in every groups.

**Comment by 1715173329** [comment]
> 好啊，反正咱对于这里而言只有 noise，这边建议您直接 reply to me with /ban in every groups.

继续阴阳怪气 & 转移话题，请

**Comment by AmadeusGhost** [comment]
> 继续阴阳怪气 & 转移话题，请

？您爱咋想就咋想，不过吧，咱只希望 “我可以送你出去” 那个“你”指的是我而不是 reply to others.

**Comment by 1715173329** [comment]
> > 继续阴阳怪气 & 转移话题，请
> 
> ？您爱咋想就咋想，不过吧，咱只希望 “我可以送你出去” 那个“你”指的是我而不是 reply to others.

你也大可不必动不动就拿退出来威胁谁
也不必装作弱势像是我 qj 了你一样
也不必说得好像我没事喜欢迫害别人一样

如果你自己都不认为自己是 member，我再挽留也毫无意义

**Comment by AmadeusGhost** [comment]
> 你也大可不必动不动就拿退出来威胁谁

威胁…？我求您把我拉黑了行不行
