### ISSUE TITLE
18.06分支使用GCC10.2编译到htop时出错

### ISSUE THREAD

**Issue by ghost** [project-openwrt/openwrt#206]

**Comment by ksong008** [comment]
1、你那个图没有任何意义
2、尝试删除htop的patches，再编译

**Comment by 101818** [comment]
> 1、你那个图没有任何意义
> 2、尝试删除htop的patches，再编译

哦。我没有发图吖

**Comment by 101818** [comment]
取消编译htop结果到shadowsocksr-libev过不了

**Comment by 1715173329** [comment]
@101818 不发报错日志发这个¿

**Comment by 101818** [comment]
日志在compile那里展开

**Comment by 1715173329** [comment]
@101818 呵呵，这么大堆日志我去慢慢翻么？

**Comment by 101818** [comment]
![08743582-FABC-42C5-84BF-878380C37138](https://user-images.githubusercontent.com/71375268/93483641-995eda00-f933-11ea-8078-f25b2e7a5fa2.png)

**Comment by AmadeusGhost** [comment]
那简单，不用 gcc10 即可，你这图明显不止 htop 报错
