### ISSUE TITLE
master 分支的 ddns 不能加载服务商

### ISSUE THREAD

**Issue by imoldchen** [project-openwrt/openwrt#209]
DDNS 编译时选择安装了 ddns-scripts ddns-scripts_aliyun ddns-scripts_dnspod 服务商那一栏还是没有任何内容。

**Comment by 1715173329** [comment]
@zxlhhyccc 灯爷来确认下，看看情况如何

**Comment by 1715173329** [comment]
问题找到了，这周抽空修复下。
