### ISSUE TITLE
红米AC2100编译后有两个无线

### ISSUE THREAD

**Issue by kinglasy** [project-openwrt/openwrt#210]
一开始是发现mtwifi重新出现了，不加mtwifi后，无线里面还是只有一个2.4ghz频道，没有显示5ghz。5ghz只能通过mtwifi使用，但是信号会变得拉稀，面对面都能拉稀，国庆后补上图。

暂时当我放屁吧

**Comment by 1715173329** [comment]
分支？编译配置？

**Comment by kinglasy** [comment]
> 分支？编译配置？

8号回学校再up上来，暂时当我放屁（sorry
