### ISSUE TITLE
酸酸乳 Plus+ 无法启动

### ISSUE THREAD

**Issue by xiaobaishu1** [project-openwrt/openwrt#223]
酸酸乳 Plus+ 无法启动 4.14内核

**Comment by outemancut** [comment]
Wed Nov  4 20:09:42 2020 daemon.err uhttpd[1623]: sed: /tmp/dnsmasq.ssr/gfw_base.conf: No such file or directory
Wed Nov  4 20:09:42 2020 daemon.err uhttpd[1623]: /usr/share/shadowsocksr/gfw2ipset.sh: line 38: can't create /tmp/dnsmasq.ssr/blacklist_forward.conf: nonexistent directory
Wed Nov  4 20:09:42 2020 daemon.err uhttpd[1623]: /usr/share/shadowsocksr/gfw2ipset.sh: line 39: can't create /tmp/dnsmasq.ssr/blacklist_forward.conf: nonexistent directory
Wed Nov  4 20:09:42 2020 daemon.err uhttpd[1623]: /usr/share/shadowsocksr/gfw2ipset.sh: line 40: can't create /tmp/dnsmasq.ssr/whitelist_forward.conf: nonexistent directory
Wed Nov  4 20:09:42 2020 daemon.err uhttpd[1623]: /usr/share/shadowsocksr/gfw2ipset.sh: line 41: can't create /tmp/dnsmasq.ssr/denylist.conf: nonexistent directory

**Comment by AmadeusGhost** [comment]
这跟竞斗云和 4.14 内核都没关系吧 ,,, 个人希望没事不要把插件的问题指向内核或者机器。

**Comment by 8688Add** [comment]
> 这跟竞斗云和 4.14 内核都没关系吧 ,,, 个人希望没事不要把插件的问题指向内核或者机器。

今天编译了个vssr测试了一下18.06分支,4.14内核这几天的更新确实无法启动vssr

**Comment by zxlhhyccc** [comment]
首先你要说清楚是哪个分支编译的？如果是1907或者master分支，要修改init的一个代码。。。。

**Comment by outemancut** [comment]
> 这跟竞斗云和 4.14 内核都没关系吧 ,,, 个人希望没事不要把插件的问题指向内核或者机器。

难道反馈问题连机器内核都不需要说明一下？之前18.06 4.14内核的高通4019的筋斗云可以使用 这两天更新的不能使用了 反馈一下说是指内核机器问题？

**Comment by zxlhhyccc** [comment]
请将init的这行代码改成
![image](https://user-images.githubusercontent.com/45259624/98118601-72aa3200-1ee6-11eb-97e9-f891eb08a7d9.png)

**Comment by outemancut** [comment]
> 请将init的这行代码改成
> ![image](https://user-images.githubusercontent.com/45259624/98118601-72aa3200-1ee6-11eb-97e9-f891eb08a7d9.png)

OK 我试试

**Comment by AmadeusGhost** [comment]
> 反馈一下说是指内核机器问题？

是我太菜了，理解能力堪忧，不过您原来的标题是得改改，我还以为是内核炸了
> 首先你要说清楚是哪个分支编译的？
他们不都说了是 18.06 分支嘛

**Comment by zxlhhyccc** [comment]
> > 请将init的这行代码改成
> > ![image](https://user-images.githubusercontent.com/45259624/98118601-72aa3200-1ee6-11eb-97e9-f891eb08a7d9.png)
> 
> OK 我试试

应该可以了吧。。。。

**Comment by outemancut** [comment]
find bin

> > > 请将init的这行代码改成
> > > ![image](https://user-images.githubusercontent.com/45259624/98118601-72aa3200-1ee6-11eb-97e9-f891eb08a7d9.png)
> > 
> > 
> > 好吧我试试
> 
> 应该可以了吧....

我又重新编译了一下 刷上还是一样无法启动
![QQ图片20201104221859](https://user-images.githubusercontent.com/53339509/98122612-cd925800-1eeb-11eb-8f99-236f783486f8.png)

**Comment by 1715173329** [comment]
@AmadeusGhost

最近确实又有一堆人因为“内核升级”而出现各种问题了。。
可能是最近某个 commit 导致的吧 (((

**Comment by zxlhhyccc** [comment]
> @AmadeusGhost
> 
> 最近确实又有一堆人因为“内核升级”而出现各种问题了。。
> 可能是最近某个 commit 导致的吧 (((

我怀疑是那个include/netfilter.mk问题，config-5.4已经屏蔽了CONFIG_IP6_NF_TARGET_MASQUERADE，我改回去试试。。。。

**Comment by AmadeusGhost** [comment]
> 我怀疑是那个include/netfilter.mk问题，config-5.4已经屏蔽了CONFIG_IP6_NF_TARGET_MASQUERADE，我改回去试试。。。。

您到底在干啥啊？上面说的是 18.06 您往 5.4 上扯。别改回去试了，您先看看官方的 commit message 再说，还可以去搜 linux kernel 的 commit message，再不行 make kernel_menuconfig 找 symbol，总比 xj8 猜好得多。

**Comment by zxlhhyccc** [comment]
> > 我怀疑是那个include/netfilter.mk问题，config-5.4已经屏蔽了CONFIG_IP6_NF_TARGET_MASQUERADE，我改回去试试。。。。
> 
> 您到底在干啥啊？上面说的是 18.06 您往 5.4 上扯。别改回去试了，您先看看官方的 commit message 再说，还可以去搜 linux kernel 的 commit message，再不行 make kernel_menuconfig 找 symbol，总比 xj8 猜好得多。

因为我前天master的73内核正常。。。。

**Comment by xiaobaishu1** [comment]
> @AmadeusGhost
> 
> 最近确实又有一堆人因为“内核升级”而出现各种问题了。。
> 可能是最近某个 commit 导致的吧 (((

一号那天用的 最新源码没问题 我就两天没编译而已  不过我发现了节点那里点更新节点后 第一个节点自动应用在主服务器上面 而日志上面没有显示完全 2020-10-31 10:37:09 成功解析: v2ray 节点, 沪港CN2隧道|香港电讯
2020-10-31 10:37:03 服务正在暂停
之前解析完成会有这一项
2020-10-31 10:37:03 服务正在暂停
------------end------------
------------end------------
-----------start-----------
-----------start-----------

**Comment by zxlhhyccc** [comment]
> > @AmadeusGhost
> > 最近确实又有一堆人因为“内核升级”而出现各种问题了。。
> > 可能是最近某个 commit 导致的吧 (((
> 
> 一号那天用的 最新源码没问题 我就两天没编译而已 不过我发现了节点那里点更新节点后 第一个节点自动应用在主服务器上面 而日志上面没有显示完全 2020-10-31 10:37:09 成功解析: v2ray 节点, 沪港CN2隧道|香港电讯
> 2020-10-31 10:37:03 服务正在暂停
> 之前解析完成会有这一项
> 2020-10-31 10:37:03 服务正在暂停
> ------------end------------
> ------------end------------
> -----------start-----------
> -----------start-----------

1号的肯定是没问题的

**Comment by 1715173329** [comment]
问题源于上游 commit 1a69f50dc627f6fc5860f871edec357cc0a187e6。
init 中对于附加命令的定义发生了改动，故导致部分 init 失效

**Comment by zxlhhyccc** [comment]
> 问题源于上游 commit [1a69f50](https://github.com/project-openwrt/openwrt/commit/1a69f50dc627f6fc5860f871edec357cc0a187e6)。
> init 中对于附加命令的定义发生了改动，故导致部分 init 失效

将init中得代码：EXTRA_COMMANDS=rules 改成： EXTRA_COMMAND "rules"即可解决问题。。。
