### ISSUE TITLE
请问支持c811的无线网卡驱动吗？

### ISSUE THREAD

**Issue by bike3097a** [project-openwrt/openwrt#226]
请问支持c811无线驱动吗？

**Comment by 1715173329** [comment]
@bike3097a 说明呢？详细型号呢？

**Comment by bike3097a** [comment]
> @bike3097a 说明呢？详细型号呢？

8811CU-B网卡型号。商家推荐用8811cu驱动，支持不。

**Comment by 1715173329** [comment]
@bike3097a 不支持。

**Comment by AmadeusGhost** [comment]
@bike3097a 支持，自行选上 rtl8821cu 驱动然后找商家要设置教程。
