### ISSUE TITLE
系统页面型号栏信息显示有问题

### ISSUE THREAD

**Issue by zhaoxh5** [project-openwrt/openwrt#229]
使用openwrt-19.07编译的N1固件，在系统自动跑分后型号栏显示不正常，请问是哪里的问题呢？
![image](https://user-images.githubusercontent.com/67985916/99934748-d4e5ac80-2d99-11eb-8343-5398ab4c5446.png)

**Comment by 1715173329** [comment]
杂交问题自行处理
