### ISSUE TITLE
可以增加argon_dark_purple主题吗？

### ISSUE THREAD

**Issue by cococle** [project-openwrt/openwrt#230]
可以增加argon_dark_purple主题吗？

**Comment by 1715173329** [comment]
配色插件已有，自己调。

**Comment by cococle** [comment]
请问插件名是？

2020-11-25 

ice8v8 



发件人：CN_SZTL <notifications@github.com>
发送时间：2020-11-25 12:46
主题：Re: [project-openwrt/openwrt] 可以增加argon_dark_purple主题吗？ (#230)
收件人："project-openwrt/openwrt"<openwrt@noreply.github.com>
抄送："cococle"<ice8v8@163.com>,"Author"<author@noreply.github.com>

配色插件已有，自己调。

**Comment by 1715173329** [comment]
@cococle luci-app-argon-config
