### ISSUE TITLE
kcptun目录找不到

### ISSUE THREAD

**Issue by tporwx** [project-openwrt/openwrt#233]
Master源码中没有kcptun目录吗？
其它分支已经更新到1126，但master编译出来还是1010。

**Comment by hue715** [comment]
有的，在https://github.com/project-openwrt/packages/tree/master/net/kcptun
更新feeds就可以了。

**Comment by 1715173329** [comment]
see project-openwrt/packages@0ef19e5892b36c647463870974e70426bdc95c3d.
