### ISSUE TITLE
最新的passwall安装不了

### ISSUE THREAD

**Issue by tporwx** [project-openwrt/openwrt#234]
Collected errors:
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-passwall found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-app-passwall.
make[2]: *** [package/Makefile:69: package/install] Error 255

**Comment by tporwx** [comment]
编译的是master分支

**Comment by tporwx** [comment]
为什么直接关闭了？
这个编译错误怎么解决呢？

**Comment by 1715173329** [comment]
机型？架构？勾选的软件？

**Comment by tporwx** [comment]
K3 选了ddns softethervpn passwall upnp.
相同配置我用19.07编译是成功的

**Comment by 1715173329** [comment]
Cc: @zxlhhyccc

**Comment by tporwx** [comment]
看来是xray和v2ray有冲突，取消勾选v2ray就编译成功了。
但是我用lienol的openwrt源码+passwall全选是可以编译成功的，xray和v2ray可以共存。
