### ISSUE TITLE
openwrt-19.07 分支 GitHub Actions 编译 x86_64 OpenClash 在 luci 界面找不到 OpenClash 

### ISSUE THREAD

**Issue by PassWall-OpenWrt** [project-openwrt/openwrt#239]
版本 r12429-e3fe7f8657

config 文件内容 https://paste.ubuntu.com/p/2mQd6RWFTC/

![photo_2020-12-13_12-28-18](https://user-images.githubusercontent.com/67915086/102003169-c8bc9180-3d3e-11eb-82c3-327a5eefef2a.jpg)

![photo_2020-12-13_12-28-12](https://user-images.githubusercontent.com/67915086/102003175-dd992500-3d3e-11eb-83d8-7f5aa9f6b64f.jpg)

**Comment by zxlhhyccc** [comment]
> 版本 r12429-e3fe7f8657
> 
> config 文件内容 https://paste.ubuntu.com/p/2mQd6RWFTC/
> 
> ![photo_2020-12-13_12-28-18](https://user-images.githubusercontent.com/67915086/102003169-c8bc9180-3d3e-11eb-82c3-327a5eefef2a.jpg)
> 
> ![photo_2020-12-13_12-28-12](https://user-images.githubusercontent.com/67915086/102003175-dd992500-3d3e-11eb-83d8-7f5aa9f6b64f.jpg)

你继续使用0.41.06？

**Comment by PassWall-OpenWrt** [comment]
> > 版本 r12429-e3fe7f8657
> > config 文件内容 https://paste.ubuntu.com/p/2mQd6RWFTC/
> > ![photo_2020-12-13_12-28-18](https://user-images.githubusercontent.com/67915086/102003169-c8bc9180-3d3e-11eb-82c3-327a5eefef2a.jpg)
> > ![photo_2020-12-13_12-28-12](https://user-images.githubusercontent.com/67915086/102003175-dd992500-3d3e-11eb-83d8-7f5aa9f6b64f.jpg)
> 
> 你继续使用0.41.06？

I opened this issue 10 days ago !

**Comment by PassWall-OpenWrt** [comment]
@AmadeusGhost 这个已经解决了吗？就关了？

**Comment by 1715173329** [comment]
This still doesn't work, so I would like to reopen it until resolved.
