### ISSUE TITLE
cryptopp820编译出错

### ISSUE THREAD

**Issue by ksong008** [project-openwrt/openwrt#242]
1806-k5.4
cryptopp820编译出错
![photo_2020-12-21_14-01-19](https://user-images.githubusercontent.com/54489832/102744661-529ad900-4395-11eb-8b99-1725c8a0f20d.jpg)

**Comment by AmadeusGhost** [comment]
Duplicate with #180

**Comment by ksong008** [comment]
> Duplicate with #180

重新clone来也是报错。。。

**Comment by AmadeusGhost** [comment]
试试 `git pull && git cherry-pick 162b53635815e7d606cf7627d66a25ea52d11e89`
![libcryptopp](https://user-images.githubusercontent.com/42570690/102755249-1a9d9100-43a9-11eb-8e7a-f0e28344a538.png)

**Comment by ksong008** [comment]
> 试试 `git pull && git cherry-pick 162b53635815e7d606cf7627d66a25ea52d11e89`
> ![libcryptopp](https://user-images.githubusercontent.com/42570690/102755249-1a9d9100-43a9-11eb-8e7a-f0e28344a538.png)

可能是config的问题，我load老的config就出错，我新建了一个pass
