### ISSUE TITLE
luci-app-zerotier eror One or more required fields have no value!

### ISSUE THREAD

**Issue by predators46** [project-openwrt/openwrt#247]
Plis fix luci zero tier openwrt branch 19.07.2

**Comment by 1715173329** [comment]
> Plis fix luci zero tier openwrt branch 19.07.2

Any screenshot?

**Comment by predators46** [comment]
> > Plis fix luci zero tier openwrt branch 19.07.2
> 
> Any screenshot?

![Screenshot_2021-01-02_193921](https://user-images.githubusercontent.com/31931530/103456566-508c2f00-4d32-11eb-824c-ed328ade6b09.jpg)

**Comment by 1715173329** [comment]
Click '+' besides the inputbox and then apply the modification.

**Comment by predators46** [comment]
> Click '+' besides the inputbox and then apply the modification.

thanks friends solved. there is more you have to give permission in the file /etc/init.d/zerotier

**Comment by 1715173329** [comment]
> there is more you have to give permission in the file /etc/init.d/zerotier

It should be fixed in latest git HEAD, so just please update your feeds.

**Comment by predators46** [comment]
> > there is more you have to give permission in the file /etc/init.d/zerotier
> 
> It should be fixed in latest git HEAD, so just please update your feeds.

Thanks my friend. can you add luci to tun2socks my client needs this

**Comment by 1715173329** [comment]
> Thanks my friend. can you add luci to tun2socks my client needs this

I'll be glad if you can submit a PR.

**Comment by predators46** [comment]
> > Thanks my friend. can you add luci to tun2socks my client needs this
> 
> I'll be glad if you can submit a PR.

I don't know how to create a file. i plan to combine shadowsocks and tun2socks
