### ISSUE TITLE
luci-app-ssrserver-python can not start when it uses python3

### ISSUE THREAD

**Issue by Quzard** [project-openwrt/openwrt#250]
luci-app-ssrserver-python can not start when it uses python3 but can start when python

**Comment by 1715173329** [comment]
> luci-app-ssrserver-python can not start when it uses python3 but can start when python
Could you provide any log?

**Comment by Quzard** [comment]
I don't know why it happens.
When I use this project's luci-app-ssrserver-python, it will get stuck in “ /etc/init.d/firewall restart"
However when I change all codes from python3 to python, it won't happen.

I compare

**Comment by 1715173329** [comment]
Okay, I will have a look this weekend.
The workaround is using ssr-libev-server instead.

**Comment by 1715173329** [comment]
> When I use this project's luci-app-ssrserver-python, it will get stuck in “ /etc/init.d/firewall restart"

Maybe it's caused by other apps (like zerotier fixed recently), however I cannot reproduce it.
btw, which branch do you use?

**Comment by 1715173329** [comment]
and, there's a bug that luci status still shows "Stoppted" even if it is already running.

**Comment by Quzard** [comment]
> and, there's a bug that luci status still shows "Stoppted" even if it is already running.
I use 18.06.
I will take a look at it. Thanks.

**Comment by Quzard** [comment]
> and, there's a bug that luci status still shows "Stoppted" even if it is already running.

I use 18.06.
I will take a look at it. Thank you.
