### ISSUE TITLE
编译出错（mt7621

### ISSUE THREAD

**Issue by hn-lqs** [project-openwrt/openwrt#255]
![IMG_20210114_224644](https://user-images.githubusercontent.com/68777250/104608580-035a7680-56bd-11eb-843e-ab63739e0629.jpg)

**Comment by 1715173329** [comment]
@hn-lqs 所用分支？

**Comment by 1715173329** [comment]
由于缺少必要信息且长时间未回复，此 issue 将被关闭。
如果有任何更新，可重新打开。
