### ISSUE TITLE
碰得以下问题，求助大大们

### ISSUE THREAD

**Issue by ak479822** [project-openwrt/openwrt#256]
本人用openwrt-18.06分支编译固件，编译过程很顺利，但编译好的固件发现有两个问题：
1.启用可道云时Nginx状态 显示未运行；（如图）
![image](https://user-images.githubusercontent.com/63394186/104841313-4f95f880-5901-11eb-8942-702be3a90921.png)

2.防火墙常规设置里少了"启用FullCone-NAT "选项（如图）
![image](https://user-images.githubusercontent.com/63394186/104842763-d054f480-5901-11eb-8988-23949873a116.png)
 由于本人刚开始学习编译，以上问题不知如何解决，请各位大大指教。

**Comment by AmadeusGhost** [comment]
@ak479822 第2个那个选项在“Turbo ACC 网络加速”里面。

**Comment by Fly432** [comment]
多谢各位大佬关注，问题已全部解决，谢谢。
