### ISSUE TITLE
C526a 极路由X 在每次软重启时(web界面 ，或SSH reboot)基本上2.4G 无线都无法开启。两个5G刚没问题。硬重启，拨电重启刚无此问题。

### ISSUE THREAD

**Issue by sealandwu** [project-openwrt/openwrt#258]

**Comment by 2f8ca48d** [comment]
这个是已知 bug 。官方固件同样会有 2.4G wifi 起不来的 bug 。

**Comment by AmadeusGhost** [comment]
这个机子就是这样的，没人知道为什么。

**Comment by sealandwu** [comment]
潘杂拉19.2好像软重启没问题。

**Comment by AmadeusGhost** [comment]
都一样的，lintel 说可能是 7615 芯片的 bug

**Comment by sealandwu** [comment]
谢谢开发者。辛苦了。就此关闭。

**Comment by sealandwu** [comment]
极X官方固件，我软重启了N次2.4G不丢。
潘朵拉软重启也不丢。
但Openwrt 软重启必丢。并且丢了是没软办法恢复的。
除此之外，相比B70的驱动，极X的OP驱动真的很强劲。大佬如果能修好此bug,则极X也是一代路由神器。


________________________________

**Comment by AmadeusGhost** [comment]
咋修啊，先假设是 pbboot 的问题，我有尝试过自己做 uboot，但不知道这个 nand 驱动要怎么加（
假设是 pcie reset 时间过短的问题，这个早在 linux 4.19 就已被修复，而且手动增加 reset 时间也没用（
> 潘多拉软重启也不丢

有概率丢的，多重启几次说不定就丢了，而且我手里的极X工程版软重启是不会丢的，升级的时候才会丢（
dts 也是根据从原厂固件分离出来的写的，只能说先放弃软重启吧，，，
