### ISSUE TITLE
大神好，ubuntu18.04使用环境配置脚本后，编译v2ray提示goproxy.cn的问题

### ISSUE THREAD

**Issue by jliveusa** [project-openwrt/openwrt#26]
Finding targets go: github.com/v2ray/v2ray-core@v4.22.1+incompatible: reading https://goproxy.cn/github.com/v2ray/v2ray-core/@v/v4.22.1+incompatible.mod: 404 Not Found Building targets go: github.com/v2ray/v2ray-core@v4.22.1+incompatible: reading https://goproxy.cn/github.com/v2ray/v2ray-core/@v/v4.22.1+incompatible.mod: 404 Not Found Cleaning module download cache (golang/go#27455)

**Comment by ElonH** [comment]
@jliveusa 没编译go toolchain
