### ISSUE TITLE
OPT_LAST should come after OPT_FILTER_AAAA

### ISSUE THREAD

**Issue by quintus-lab** [project-openwrt/openwrt#264]
https://github.com/project-openwrt/openwrt/blob/e392642bdd49893b243d2549815b771ba3cd175b/package/network/services/dnsmasq/patches/911-dnsmasq-filter-aaaa.patch#L18

-#define OPT_LAST           62
+#define OPT_FILTER_AAAA    62
+#define OPT_LAST           63

**Comment by 1715173329** [comment]
Please submit a PR.

**Comment by 1715173329** [comment]
Fixed with project-openwrt/openwrt@77f6cfb52dfda4b739c4aa3f2875520953d635ee.
