### ISSUE TITLE
dnsmasq

### ISSUE THREAD

**Issue by xiaobaishu1** [project-openwrt/openwrt#265]
18.06分支是否因为之前升级了dnsmasq了导致勾选“禁止解析 IPv6 DNS 记录”会出现无法正常打开网页？

![image](https://user-images.githubusercontent.com/53339509/105618347-11c53280-5e21-11eb-810e-d26cf0571b76.png)

**Comment by 1715173329** [comment]
此问题已修复，更新源码。

**Comment by xiaobaishu1** [comment]
> 此问题已修复，更新源码。

好的，应该是没问题了

**Comment by 1715173329** [comment]
@xiaobaishu1 如果已确认无误，请关闭此 issue。
