### ISSUE TITLE
Adguardhome 无法正常使用

### ISSUE THREAD

**Issue by MedyMa** [project-openwrt/openwrt#266]
编译完成后，设置好adguardhome 在，仪表盘无数据，切换重定向方式，路由器断网

**Comment by ksong008** [comment]
@MedyMa 什么分支啊

**Comment by MedyMa** [comment]
18.06分支

**Comment by MedyMa** [comment]
![B5FE5C93-3055-415A-81BB-4AD2CCD872C4](https://user-images.githubusercontent.com/75345465/105618934-0c1f1b00-5e28-11eb-9e9a-50d4e87165cf.png)
编译时用的这两个包
