### ISSUE TITLE
dalao请问你的仓库是否也有lean openwrt/package/lean/default-settings/files/zzz-default-settings

### ISSUE THREAD

**Issue by willisworley** [project-openwrt/openwrt#271]
openwrt/package/lean/default-settings/files/zzz-default-settings

dalao请问你的仓库是否也有类似的文件，改设置不生效啊，如 uhttp 访问 ip，密码等

**Comment by AmadeusGhost** [comment]
@willisworley 发 issue 前建议先在代码里搜索下。。
