### ISSUE TITLE
 关于石像鬼luci

### ISSUE THREAD

**Issue by fuqiang03** [project-openwrt/openwrt#45]
如图
![QQ截图20200227124320](https://user-images.githubusercontent.com/26851715/75412858-c4b1b580-595e-11ea-8c98-cb03496e2a61.png)
我用的是官方主库代码(全部)
不知道为什么没有显示
石像鬼都是这里的代码

config global 'global'

配置文件 要不看不见开关

**Comment by 1715173329** [comment]
如使用官方源码，请自行解决移植问题，我们不提供技术支持。
