### ISSUE TITLE
关于gotop

### ISSUE THREAD

**Issue by fuqiang03** [project-openwrt/openwrt#49]
关于gotop
![QQ截图20200306195234](https://user-images.githubusercontent.com/26851715/76081447-1653e300-5fe4-11ea-852f-f4f84680caf5.png)
这个仅在master下修改编译成功
![QQ截图20200306195359](https://user-images.githubusercontent.com/26851715/76081532-4a2f0880-5fe4-11ea-86f0-275586930773.png)
但是会有适配的控制页面吗

**Comment by 1715173329** [comment]
改这个有什么必要么。。

**Comment by fuqiang03** [comment]
原来的会说no matching versions for quer "latest"

**Comment by 1715173329** [comment]
并未检索到你所说的 `no matching versions for quer "latest"` 错误，请提交相关截图。

**Comment by 1715173329** [comment]
> 但是会有适配的控制页面吗

本插件为命令行工具，没有LuCI

**Comment by fuqiang03** [comment]
![QQ截图20200306200347](https://user-images.githubusercontent.com/26851715/76082163-ae9e9780-5fe5-11ea-96aa-e7683f966fec.png)

**Comment by fuqiang03** [comment]
可惜了挺好看的

**Comment by 1715173329** [comment]
![image](https://user-images.githubusercontent.com/22235437/76082285-f6bdba00-5fe5-11ea-9bd8-4b785829f4f8.png)
我觉得这是你自己的问题🙃

**Comment by fuqiang03** [comment]
嗯嗯

**Comment by fuqiang03** [comment]
arm构架?

**Comment by 1715173329** [comment]
![image](https://user-images.githubusercontent.com/22235437/76082646-d2aea880-5fe6-11ea-8bf3-d2a6988c4ab1.png)
如果你觉得有异议，那么这次我使用了OP官方最新源码为x86_64架构进行构建，没有任何问题

**Comment by fuqiang03** [comment]
嗯嗯

**Comment by 1715173329** [comment]
关于这个问题，你可以参考下
https://github.com/golang/go/issues/27215

**Comment by fuqiang03** [comment]
好的谢谢
