### ISSUE TITLE
更新uboot后编译X86失败，mkimage出错

### ISSUE THREAD

**Issue by jliveusa** [project-openwrt/openwrt#5]
make[3]: Entering directory '/home/fly/ctcgfw/tools/mkimage'
make -C /home/fly/ctcgfw/build_dir/host/u-boot-2019.07 HOSTCFLAGS="-O2 -I/home/fly/ctcgfw/staging_dir/host/include " HOSTLDFLAGS="-L/home/fly/ctcgfw/staging_dir/host/lib " no-dot-config-targets=tools-only CONFIG_MKIMAGE_DTC_PATH=dtc CONFIG_FIT_SIGNATURE=y tools-only
make[4]: Entering directory '/home/fly/ctcgfw/build_dir/host/u-boot-2019.07'
  HOSTCC  scripts/basic/fixdep
  CHK     include/config/uboot.release
  CHK     include/generated/version_autogenerated.h
  CHK     include/generated/timestamp_autogenerated.h
  HOSTCC  tools/mkenvimage.o
  HOSTCC  tools/os_support.o
  HOSTCC  tools/lib/crc32.o
In file included from ././include/compiler.h:46:0,
                 from <command-line>:0:
/home/fly/ctcgfw/staging_dir/host/include/byteswap.h:2:2: warning: #include_next is a GCC extension
 #include_next <byteswap.h>
  ^~~~~~~~~~~~
  HOSTLD  tools/mkenvimage
  HOSTCC  tools/aisimage.o
  HOSTCC  tools/atmelimage.o
  HOSTCC  tools/common/image-sig.o
In file included from tools/common/image-sig.c:1:0:
./tools/../common/image-sig.c: In function 'fit_image_setup_verify':
./tools/../common/image-sig.c:188:56: error: expected expression before ')' token
  if (fdt_totalsize(fit) > CONFIG_FIT_SIGNATURE_MAX_SIZE) {
                                                        ^
scripts/Makefile.host:114: recipe for target 'tools/common/image-sig.o' failed
make[5]: *** [tools/common/image-sig.o] Error 1
Makefile:1788: recipe for target 'tools-only' failed
make[4]: *** [tools-only] Error 2
make[4]: Leaving directory '/home/fly/ctcgfw/build_dir/host/u-boot-2019.07'
Makefile:48: recipe for target '/home/fly/ctcgfw/build_dir/host/u-boot-2019.07/.built' failed
make[3]: *** [/home/fly/ctcgfw/build_dir/host/u-boot-2019.07/.built] Error 2
make[3]: Leaving directory '/home/fly/ctcgfw/tools/mkimage'
time: tools/mkimage/compile#0.58#0.26#0.94
tools/Makefile:155: recipe for target 'tools/mkimage/compile' failed
make[2]: *** [tools/mkimage/compile] Error 2
make[2]: Leaving directory '/home/fly/ctcgfw'
tools/Makefile:153: recipe for target '/home/fly/ctcgfw/staging_dir/target-x86_64_musl/stamp/.tools_compile_yynyyyyynyyyyynyynnnyyyynyyyyyyyyyyyyyyynyyynynnyyynnyy' failed
make[1]: *** [/home/fly/ctcgfw/staging_dir/target-x86_64_musl/stamp/.tools_compile_yynyyyyynyyyyynyynnnyyyynyyyyyyyyyyyyyyynyyynynnyyynnyy] Error 2
make[1]: Leaving directory '/home/fly/ctcgfw'
/home/fly/ctcgfw/include/toplevel.mk:216: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by 1715173329** [comment]
Well, try to check 1bc395a.
