### ISSUE TITLE
关于mtk7621无线

### ISSUE THREAD

**Issue by a528596516** [project-openwrt/openwrt#50]
WiFi计划在5.0.2无线驱动上并不生效，到时间后仍不会自动关闭无线，勾选即使有设备连接也强制关闭 WiFi也无法生效，同步最新源码后问题依旧,希望能解决一下

**Comment by AmadeusGhost** [comment]
闭源去掉其它插件控制不了很正常

**Comment by Aes64X** [comment]
> WiFi计划在5.0.2无线驱动上并不生效，到时间后仍不会自动关闭无线，勾选即使有设备连接也强制关闭 WiFi也无法生效，同步最新源码后问题依旧,希望能解决一下

死心吧，无解。

**Comment by 1715173329** [comment]
@a528596516 MTK无人权，不必询问。

**Comment by 1715173329** [comment]
如有必要自行编写脚本管理启停即可。
