### ISSUE TITLE
Passwall编译出来，没有负载均衡这一操作页面，谷歌连接总是显示失败，但能上网

### ISSUE THREAD

**Issue by Zhang-Shijun** [project-openwrt/openwrt#51]
K2P，用此仓库代码，Passwall编译出来，没有负载均衡这一操作页面（就是passwall首页有负载均衡图标，但是passwall的菜单中没有负载均衡操作菜单），谷歌连接总是显示失败，但能上谷歌。

**Comment by 1715173329** [comment]
负载均衡，HAProxy编译了么？
显示失败，手动输入相关命令行看看

**Comment by 1715173329** [comment]
Closed due timeout.
