### ISSUE TITLE
RTL8821CU编译出错

### ISSUE THREAD

**Issue by CMCCAdmin** [project-openwrt/openwrt#52]
RTL8821CU无论是x86 还是arm sunxi平台均编译失败希望能修复，谢谢
错误代码http://140.238.10.55/111.PNG

**Comment by 1715173329** [comment]
当前源码在4.19内核下编译会出现问题。。
稍后进行处理

**Comment by 1715173329** [comment]
Fixed in 6aaaf6a, by @AmadeusGhost dalao.
