### ISSUE TITLE
rtl8821cu 依然无法编译通过

### ISSUE THREAD

**Issue by CMCCAdmin** [project-openwrt/openwrt#53]
大神添加补丁后我又试了下，驱动编译到一半报错。

In file included from /home/pc/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/rtl8821cu-20200302/include/osdep_service_linux.h:83:0,
                 from /home/pc/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/rtl8821cu-20200302/include/osdep_service.h:50,
                 from /home/pc/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/rtl8821cu-20200302/include/drv_types.h:27,
                 from /home/pc/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/rtl8821cu-20200302/core/rtw_mp.c:16:
./include/linux/ieee80211.h:1442:0: note: this is the location of the previous definition
 #define IEEE80211_MAX_AMPDU_BUF  0x100
 
/home/pc/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/rtl8821cu-20200302/core/rtw_mp.c: In function 'rtfloor':
/home/pc/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/rtl8821cu-20200302/core/rtw_mp.c:31:5: error: '-mgeneral-regs-only' is incompatible with floating-point argument
 int rtfloor(float x)
     ^~~~~~~
scripts/Makefile.build:303: recipe for target '/home/pc/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/rtl8821cu-20200302/core/rtw_mp.o' failed
make[5]: *** [/home/pc/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/rtl8821cu-20200302/core/rtw_mp.o] Error 1
Makefile:1520: recipe for target '_module_/home/pc/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/rtl8821cu-20200302' failed
make[4]: *** [_module_/home/pc/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/rtl8821cu-20200302] Error 2
make[4]: Leaving directory '/home/pc/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/linux-4.19.108'
Makefile:62: recipe for target '/home/pc/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/rtl8821cu-20200302/.built' failed
make[3]: *** [/home/pc/lede/build_dir/target-aarch64_cortex-a53_musl/linux-sunxi_cortexa53/rtl8821cu-20200302/.built] Error 2
make[3]: Leaving directory '/home/pc/lede/package/kernel/rtl8821cu'
time: package/kernel/rtl8821cu/compile#85.53#7.36#104.09
package/Makefile:111: recipe for target 'package/kernel/rtl8821cu/compile' failed
make[2]: *** [package/kernel/rtl8821cu/compile] Error 2
make[2]: Leaving directory '/home/pc/lede'
package/Makefile:107: recipe for target '/home/pc/lede/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_compile' failed
make[1]: *** [/home/pc/lede/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/pc/lede'
/home/pc/lede/include/toplevel.mk:225: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by AmadeusGhost** [comment]
这个是因为arm64比较特殊，我跑一下sunxi的看看
