### ISSUE TITLE
hdparm 編譯出錯

### ISSUE THREAD

**Issue by kai456789** [project-openwrt/openwrt#9]
如圖 勾選 hdparm 編譯會失敗
CPU為高通IQ4019 機型 ACRH17
![1570069741030](https://user-images.githubusercontent.com/720118/66095200-4f1d0580-e5c9-11e9-8001-3027c867b8b7.jpg)

**Comment by 1715173329** [comment]
@kai456789 请更新feeds源并重新编译

**Comment by kai456789** [comment]
更新feeds源後 出現兩個hdparm 
![1570082635037](https://user-images.githubusercontent.com/720118/66103046-ffe5cd80-e5e6-11e9-8f2a-8700ac8d5792.jpg)
編譯下去報錯 
![1570082760002](https://user-images.githubusercontent.com/720118/66103070-1db33280-e5e7-11e9-8491-2528c581d397.jpg)

**Comment by 1715173329** [comment]
根据检测，目前是官方的源码出现问题，请暂时取消勾选并等待处理。

**Comment by 1715173329** [comment]
fixed at https://github.com/project-openwrt/packages/commit/e343cfa080b59205abc102d9cc4159cf408b8b0a.
